/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.webdsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Back</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.webdsl.WebdslPackage#getBack()
 * @model
 * @generated
 */
public interface Back extends Code
{
} // Back
