/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.webdsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.webdsl.Back;
import org.xtext.example.mydsl.webdsl.WebdslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Back</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BackImpl extends CodeImpl implements Back
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BackImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return WebdslPackage.Literals.BACK;
  }

} //BackImpl
