/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.generator;

import java.util.Iterator;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import webdsl.*;
import com.google.inject.Inject;
/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class MyDslGenerator extends AbstractGenerator {
	
	public static <T> Iterable<T> toIterable(final Iterator<T> iterator) {
		if (iterator == null)
			throw new NullPointerException("iterator");
		return new Iterable<T>() {
			public Iterator<T> iterator() {
				return iterator;
			}
		};
	}
	
	@Inject public IQualifiedNameProvider nameProvider ;
	
	@Override
	public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
	
		 for (Application e : IterableExtensions.filter(toIterable(resource.getAllContents()), Application.class)) {
	            fsa.generateFile(
	            	nameProvider.getFullyQualifiedName(e).toString() + ".java",
	                compile(e));
	        }
	}
	
	private CharSequence compile(Application e) {
		// TODO Auto-generated method stub
		return null;
	}
	
	private CharSequence compile(Code e) {
		// TODO Auto-generated method stub
		return null;
	}
	
	private CharSequence compile(Front e) {
		// TODO Auto-generated method stub
		return null;
	}
	
	private CharSequence compile(Back e) {
		// TODO Auto-generated method stub
		return null;
	}
	private CharSequence compile(Language e) {
		// TODO Auto-generated method stub
		return null;
	}
	private CharSequence compile(Interceptor e) {
		// TODO Auto-generated method stub
		return null;
	}
	private CharSequence compile(Requisition e) {
		// TODO Auto-generated method stub
		return null;
	}
	
}
